name: Coverage

on:
  push:
    branches: master

jobs:
  upload-coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: hecrj/setup-rust-action@master
      with:
        rust-version: stable
    - uses: actions/setup-python@v1
      with:
        python-version: 3.7
    
    - name: Setup python dependencies
      run: python -m pip install pyftpdlib

    - name: Install coverage tool
      run: cargo install cargo-tarpaulin --force

    - name: Build project
      run: cargo build --verbose
    
    - name: Run tests
      env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: cargo tarpaulin --out Xml && bash <(curl -s https://codecov.io/bash)