name: Tests

on: push

jobs:
  windows-test:
    runs-on: windows-latest
        
    steps:
    - uses: actions/checkout@v1
    - uses: hecrj/setup-rust-action@master
      with:
        rust-version: stable
    - uses: actions/setup-python@v1
      with:
        python-version: 3.7
    
    - name: Setup python dependencies
      run: python -m pip install pyftpdlib
    
    - name: Build project
      run: cargo build --verbose
    
    - name: Test project
      run: cargo test external --verbose
  
  macos-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - uses: hecrj/setup-rust-action@master
      with:
        rust-version: stable
    - uses: actions/setup-python@v1
      with:
        python-version: 3.7
    
    - name: Setup python dependencies
      run: python -m pip install pyftpdlib
    
    - name: Build project
      run: cargo build --verbose
    
    - name: Test project
      run: cargo test external --verbose
  
  linux-test:
    runs-on: ubuntu-latest
    services:
      ftp_server:
        image: adilsinho/ftp-server
        ports:
        - 20:20
        - 21:21
        - 2558:2558
        - 2559:2559

    steps:
    - uses: actions/checkout@v1
    - uses: hecrj/setup-rust-action@master
      with:
        rust-version: stable
    - uses: actions/setup-python@v1
      with:
        python-version: 3.7
    
    - name: Setup python dependencies
      run: python -m pip install pyftpdlib
    
    - name: Build project
      run: cargo build --verbose
    
    - name: Test project
      run: cargo test --verbose
      env:
        SERVER_HOSTNAME: ftp
  
  nigthly-test:
    runs-on: ubuntu-latest
    services:
      ftp:
        image: adilsinho/ftp-server
        ports:
        - 20:20
        - 21:21
        - 2558:2558
        - 2559:2559

    steps:
    - uses: actions/checkout@v1
    - uses: hecrj/setup-rust-action@master
      with:
        rust-version: nightly
    - uses: actions/setup-python@v1
      with:
        python-version: 3.7
    
    - name: Setup python dependencies
      run: python -m pip install pyftpdlib
    
    - name: Build project
      run: cargo build --verbose
    
    - name: Test project
      run: cargo test --verbose
      env:
        SERVER_HOSTNAME: ftp
  
  legacy-test:
    runs-on: ubuntu-latest
    services:
      ftp_server:
        image: adilsinho/ftp-server
        ports:
        - 20:20
        - 21:21
        - 2558:2558
        - 2559:2559
        
    steps:
    - uses: actions/checkout@v1
    - uses: hecrj/setup-rust-action@master
      with:
        rust-version: 1.36.0
    - uses: actions/setup-python@v1
      with:
        python-version: 3.7
    
    - name: Setup python dependencies
      run: python -m pip install pyftpdlib
  
    - name: Build project
      run: cargo build --verbose
    
    - name: Test project
      run: cargo test --verbose
      env:
        SERVER_HOSTNAME: ftp
